# Build flask api backend
FROM python:3.10.5
WORKDIR /osd

RUN mkdir ./api
COPY Backend/api/requirements.txt Backend/api/.env Backend/api/config.py Backend/api/__init__.py Backend/api/app.py Backend/api/models.py ./api
RUN pip install -r ./api/requirements.txt
ENV SQLALCHEMY_DATABASE_URI mysql+pymysql://root:password@db/osd_db

EXPOSE 5000
CMD ["gunicorn", "-b", ":3000", "api:create_app()"]