# Build react frontend
FROM node:16-alpine as build-step
WORKDIR /osd
ENV PATH /Frontend/office-supply-depot/node_modules/.bin:$PATH
COPY Frontend/office-supply-depot/package.json Frontend/office-supply-depot/package-lock.json ./
COPY Frontend/office-supply-depot/src ./src
COPY Frontend/office-supply-depot/public ./public
RUN npm install
RUN npm run build

# Build nginx with build files from previous step
FROM nginx:stable-alpine
COPY --from=build-step /osd/build /usr/share/nginx/html
COPY nginx.default.conf /etc/nginx/conf.d/default.conf