services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: office-supply-depot-server
    ports:
      - "3000:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: office-supply-depot-api
    restart: always
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: mysql:8
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
