services:
  db:
    volumes:
      - ../Backend/api/sql:/docker-entrypoint-initdb.d
    image: mysql:8
    hostname: db
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: password
  server:
    build:
      context: ../Backend/api
      dockerfile: Dockerfile.server
    restart: always
    hostname: server
    depends_on:
    - db
  client:
    build:
      context: ../Frontend/office-supply-depot
      dockerfile: Dockerfile.client
    depends_on:
    - server
    - db
    restart: always
    ports: 
      - "80:80"
