# Build react frontend
FROM node:16-alpine as build-step
WORKDIR /osd
ENV PATH node_modules/.bin:$PATH
COPY package.json package-lock.json ./
COPY src ./src
COPY public ./public
RUN npm config set legacy-peer-deps true
RUN npm install
RUN npm run build

# Build nginx reverse proxy
FROM nginx:stable-alpine
COPY --from=build-step /osd/build /usr/share/nginx/html
COPY nginx.default.conf /etc/nginx/conf.d/default.conf